// This file is generated by Slice Machine. Update with care!

import ClientCards from './ClientCards';
import ContactForm from './ContactForm';
import Hero from './Hero';
import Image from './Image';
import ImageCards from './ImageCards';
import JobPost from './JobPost';
import Quote from './Quote';
import Text from './Text';
import TextWithImage from './TextWithImage';

export {
	ClientCards,
	ContactForm,
	Hero,
	Image,
	ImageCards,
	JobPost,
	Quote,
	Text,
	TextWithImage,
};

export const components = {
	client_cards: ClientCards,
	contact_form: ContactForm,
	hero: Hero,
	image: Image,
	image_cards: ImageCards,
	job_post: JobPost,
	quote: Quote,
	text: Text,
	text_with_image: TextWithImage,
};
